### PR TITLE
Space 48 - Hiring process

### PR DESCRIPTION
**Pull request by grecdev**

### CODE REVIEW

**Comment by punkstar** [comment]
Hey @grecdev - can you open this on your own fork please?

**Comment by grecdev** [comment]
Can you please explain me how to do that ?

**Comment by punkstar** [comment]
Sure - make a branch on https://github.com/grecdev/ui-exercise-forms and open a pull request from that branch into your master branch on https://github.com/grecdev/ui-exercise-forms.

**Comment by grecdev** [comment]
Ok so i've created another branch on my repository named `grecdev`. But the `master` branch on my repository is the same as the `grecdev` branch. Should i get the original `master branch` from `space48` and replace it with the master branch from my repo and then create a pull request on `grecdev` branch to `master` branch which both are on my own repo right ?

**Pull request closed without merging**
